export const CharDataBase = [
  {
    id: "1-1",
    chName: "茅森月歌",
    styleName: "Attack or Music",
    rarity: "A",
    Ult: "N/A",
    Skill: "クロス斬り",
    SearchKey: "茅森月歌 kayamoriruka Attack or Music",
  },
  {
    id: "1-2",
    chName: "茅森月歌",
    styleName: "戦場のフレット",
    rarity: "S",
    Ult: "N/A",
    Skill: "フルブレイカー",
    SearchKey: "茅森月歌 kayamoriruka kayamori ruka 戦場のフレット",
  },
  {
    id: "1-3",
    chName: "茅森月歌",
    styleName: "閃光のサーキットバースト",
    rarity: "SS",
    Ult: "夢幻泡影",
    Skill: "リカバー",
    SearchKey: "茅森月歌 kayamori ruka 閃光のサーキットバースト",
  },
  {
    id: "2-1",
    chName: "和泉ユキ",
    styleName: "Attack or March",
    rarity: "A",
    Ult: "N/A",
    Skill: "ブレイクバースト",
    SearchKey:
      "和泉ユキ izumiyuki izumi yuki yukki ユッキ ゆっき 和泉ゆき Attack or March",
  },
  {
    id: "2-2",
    chName: "和泉ユキ",
    styleName: "夢幻のSleeping Ocelot",
    rarity: "S",
    Ult: "N/A",
    Skill: "クールダウン",
    SearchKey:
      "和泉ユキ izumiyuki izumi yuki yukki ユッキ ゆっき 和泉ゆき 夢幻のSleeping Ocelot",
  },
  {
    id: "2-3",
    chName: "和泉ユキ",
    styleName: "",
    rarity: "SS",
    Ult: "流星",
    Skill: "",
    SearchKey: "和泉ユキ izumiyuki izumi yuki yukki ユッキ ゆっき 和泉ゆき",
  },
  {
    id: "3-1",
    chName: "逢川めぐみ",
    styleName: "Plain or Wild",
    rarity: "A",
    Ult: "N/A",
    Skill: "スタンブレード",
    SearchKey:
      "逢川めぐみ aikawamegumi aikawa megumi meguminn めぐみん Plain or Wild",
  },
  {
    id: "3-2",
    chName: "逢川めぐみ",
    styleName: "Impact Stream",
    rarity: "S",
    Ult: "N/A",
    Skill: "ハードブレード",
    SearchKey: "逢川めぐみ aikawamegumi aikawa megumi meguminn めぐみん Ikki",
  },
  {
    id: "3-3",
    chName: "逢川めぐみ",
    styleName: "Ikki",
    rarity: "SS",
    Ult: "N/A",
    Skill: "ハードブレード",
    SearchKey:
      "逢川めぐみ aikawamegumi aikawa megumi meguminn めぐみん Impact Stream",
  },
  {
    id: "4-1",
    chName: "東城つかさ",
    styleName: "Ikki",
    rarity: "A",
    Ult: "N/A",
    Skill: "ハードブレード",
    SearchKey: "東城つかさ toujotsukasa tsukasacchi つかさっち",
  },
];
